### ISSUE TITLE
Evaluation of Your Assignment for Computer-Controlled Cutting Week

### ISSUE THREAD

**Issue by BehnazNorouzi** [palosaari/fablab#1]
Hi Antti,

Good work. Good to hear that you now know lots of things about laser cutting and vinyl cutting. Hard work pays off at the end :)
And yes, this course needs a considerable amount of time to spend on, because there are lots of things to learn and to do as well as documenting in detail what you did and learnt. If you engage enough in 2D modeling and 3D modeling during the previous week's assignment (Computer-aided design) then the workload of this week's assignment might be a bit lighter. 

**Please consider the followings to fix**:

1. ~Explain the steps that you took for vinyl cutting; for example, explain about what steps did you take to prepare the machine? for example, you can talk about loading and unloading the vinyl, adjusting pinch rollers and white grit marks, the display with 3 options (roll, edge, piece), what happened when you chose each of them (measuring width/height and showing the dimensions on the display, etc.), did you send the cut order from Inkscape or CutStudio and how, and etc. So, basically explain everything that you did to get it worked for you.~
2. ~Name the tools that you used for weeding; e.g., tweezers.~
3. ~Explain the use of adhesive transfer sheet after you weed.~
4. ~Add a hero image of your vinyl cutting result that shown you have attached the sticker to an object.~
5. ~In 'Power, frequency, speed tests' section, talk also about your observation for the engraving test that we did with different values for power. And also talk about the DPI test that with did with the smaller laser cutter.~
6. ~To complete the explanation of how you designed your press-fit kit, add the names of the tools that you used to design your press-fit construction kit in FreeCad and how you accessed the tools. For example; I drew a rectangle (tools > rectangle).~
7. ~JOG. It is staring point of your laser print - upper left corner of document you sent to laser. >> Jog is not the start point, by using jog, you set the start point which is origin (top left corner).~
8. ~FOCUS. It is distance between laser beam and material >> Focus is adjusting the right distance between laser beam and material.~
9. ~Wait minute or so after laser is finished before opening the lid. >> wait 1 minute or so~

**What to do next**:
- Fix your documentation considering my suggestions above. Then, write a comment under this issue when your documentation is ready.

Bests,
Behnaz

**Comment by palosaari** [comment]
Thanks for the feedback,

1. done
2. done
3. done
4. done
5. engraving part is missing, but the rest are done
6. done. That was done already. FreeCAD tool name used is polyline on Sketcher workbench and tool is found behind the toolbar icon.
7. done
8. done
9. done

br,
Antti

**Comment by BehnazNorouzi** [comment]
Hi Antti, 

Thanks for your comment.

Everything looks good. However, please consider fixing this minor issues:
- Roller locations are used to detect material width >> to detect the width of the cut area; because the material width can be larger that that.

I close this issue now. Your computer-controlled cutting week assignment is passed from my point of view. :)

Bests,
Behnaz
